---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes
  listen: "Reload systemd daemon"

- name: Restart tileserver
  ansible.builtin.systemd:
    name: tileserver
    state: restarted
    daemon_reload: yes
  # Ensures a rolling restart by processing only one host at a time
  # The next host will only start once this host has passed the health check
  throttle: 1
  listen: "Restart tileserver"

- name: Reset failure counter for tileserver.service
  ansible.builtin.shell: |
    systemctl reset-failed tileserver.service
  listen: Restart tileserver

- name: Check tileserver is back up
  ansible.builtin.uri:
    url: "http://localhost:{{ tileserver_port }}"
    status_code: 200
  retries: 30
  delay: 10
  throttle: 1
  listen: "Restart tileserver"

- name: Check nginx conf
  ansible.builtin.command: "/usr/sbin/nginx -t"
  become: yes
  listen: "Restart nginx"

- name: Restart nginx service
  ansible.builtin.service:
    name: nginx
    state: restarted
  listen: "Restart nginx"
