- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: restart apt daily upgrade timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    enabled: true