---
- name: Copy OTP quadlet container config
  template:
    src: systemd/{{ item }}
    dest: /etc/containers/systemd/
    owner: root
    group: root
  with_items:
    - otp.container
  notify: Reload OTP service
  register: otp

- name: Start service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - otp.service
  register: otp

- name: Caddyfile
  ansible.builtin.template:
    src: templates/otp.caddy
    dest: /etc/caddy/
    owner: caddy
    group: caddy
    mode: 0660
  notify: Restart caddy
