---
- name: Reset failure counter for otp.service
  ansible.builtin.shell: |
    systemctl reset-failed tilemaker.service
  listen: Restart tilemaker

- name: Restart tilemaker service
  service:
    name: tilemaker
    state: restarted
  listen: Restart tilemaker
