---
- name: Install prometheus-node-exporter
  ansible.builtin.package:
    name: prometheus-node-exporter
    state: present

- name: Start and enable prometheus-node-exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: started
    enabled: yes
