#! /bin/bash -e

d=$(date --iso-8601=date)

file=/var/lib/containers/storage/volumes/grafana-storage/_data/grafana.db

echo "Sending file to off-site storage"
curl --silent --show-error --fail -T "${file}" -u 'grafana-backup:{{ grafana_backup_password }}' "https://nextcloud.leonard.io/remote.php/dav/files/grafana/{{ grafana_backup_folder }}/grafana-${d}.db"
