---

- name: Start graph build
  ansible.builtin.shell: |
    systemctl reset-failed graph-build

- name: Start graph build
  ansible.builtin.systemd:
    state: restarted
    name: graph-build
    daemon_reload: true