---
tileserver_version: "v5.0.0"
tileserver_work_dir: "/var/tileserver/"
tileserver_cache_dir: "{{ tileserver_work_dir }}/cache/"
tileserver_port: 5000
tileserver_cache_port: 5001
tileserver_allowed_referrers:
  - "{{ tileserver_domain }}"
tileserver_tile_margin: 50
tileserver_cache_settings:
  - filetype: png
    server_cache: "1d"
    browser_cache: 3600
  - filetype: pbf
    server_cache: "15m"
    browser_cache: 3600
# extra styles to be deployed
# place in ./templates/tileserver/foo.json
tileserver_extra_styles: []